### ISSUE TITLE
Create DetailHeaderLayout Component

### ISSUE THREAD

**Issue by NoHara42** [devhausleipzig/camp-8-midterm-group-1#30]
Create a layout for the header that is provided on the movie detail, select seats, select time, and select seats pages.
The layout takes children as content to be placed on the detail page.
The back button takes you to the last visited page.

Props: Header title

**Comment by ReallyBoard123** [comment]
Dear team, it isn't easy to understand your organizational structure. I see that @ArthiRagothaman has been assigned to this issue, but I noticed that @TheDoplarEffect has made a pull request.
