### ISSUE TITLE
Handle Login

### ISSUE THREAD

**Issue by dnmct** [devhausleipzig/camp-8-midterm-group-1#49]
## Steps

- [x] Refactor the login form to update the store and set a token
- [x] Statically check for one or more email-password combinations
- [x] Show an error beneath the form if credentials are incorrect

Blocked by #47

**Comment by TheDoplarEffect** [comment]
I have updated branch 49 to include a simple Salt and hash program.
As a general rule of thumb we shouldn't store users passwords as plain text.

Basic process is:

- For each unique user (each email address) we create a unique salt (a very long complicated string)
-  To create a hashed password we have to include the password the user typed and the salt into the hash function.  This creates a very long and complicated string.
- We save the users email, salt, and hashed password as plain text in out db.json or wherever.
- Every time we get a new log in attempt, we have to take the email address, find that users salt, generate the hashed password again with that salt and the users input.  and check if the result is equal to the hashed password we stored

**Comment by ReallyBoard123** [comment]
To clarify, I believe "statically check" just means that there is a plaintext password either hardcoded or saved in local storage, and what a user types into the password input field should be compared against the hardcode/locally stored plaintext password.
